-- Art Dental - tabela de consultas
-- Execute no Supabase em: SQL Editor > New query > Run
-- Requer a tabela public.pacientes criada anteriormente.

create table if not exists public.consultas (
    id bigint generated by default as identity primary key,
    paciente_id bigint not null,
    profissional text not null,
    data_consulta date not null,
    hora_consulta time not null,
    tipo text not null default 'Consulta',
    status text not null default 'Agendada',
    observacoes text,
    criado_em timestamptz not null default now(),
    atualizado_em timestamptz not null default now(),

    constraint consultas_paciente_id_fkey
        foreign key (paciente_id)
        references public.pacientes(id)
        on delete restrict,

    constraint consultas_profissional_valido
        check (char_length(trim(profissional)) >= 2),

    constraint consultas_tipo_valido
        check (tipo in ('Consulta', 'Avaliação', 'Retorno', 'Procedimento')),

    constraint consultas_status_valido
        check (status in ('Agendada', 'Confirmada', 'Aguardando confirmação', 'Finalizada', 'Cancelada'))
);

-- Impede dois atendimentos com o mesmo profissional no mesmo horário.
create unique index if not exists consultas_profissional_horario_unique
on public.consultas (lower(profissional), data_consulta, hora_consulta)
where status <> 'Cancelada';

-- Índices para as consultas mais comuns.
create index if not exists consultas_paciente_idx
on public.consultas (paciente_id);

create index if not exists consultas_data_idx
on public.consultas (data_consulta);

create index if not exists consultas_data_hora_idx
on public.consultas (data_consulta, hora_consulta);

-- Atualiza atualizado_em automaticamente.
create or replace function public.atualizar_timestamp_consulta()
returns trigger
language plpgsql
set search_path = public
as $$
begin
    new.atualizado_em = now();
    return new;
end;
$$;

drop trigger if exists consultas_atualizado_em on public.consultas;

create trigger consultas_atualizado_em
before update on public.consultas
for each row
execute function public.atualizar_timestamp_consulta();

-- Segurança.
alter table public.consultas enable row level security;

revoke all on table public.consultas from anon;
grant select, insert, update, delete on table public.consultas to authenticated;
grant usage, select on sequence public.consultas_id_seq to authenticated;

drop policy if exists "consultas_select_autenticado" on public.consultas;
drop policy if exists "consultas_insert_autenticado" on public.consultas;
drop policy if exists "consultas_update_autenticado" on public.consultas;
drop policy if exists "consultas_delete_autenticado" on public.consultas;

create policy "consultas_select_autenticado"
on public.consultas
for select
to authenticated
using (true);

create policy "consultas_insert_autenticado"
on public.consultas
for insert
to authenticated
with check (true);

create policy "consultas_update_autenticado"
on public.consultas
for update
to authenticated
using (true)
with check (true);

create policy "consultas_delete_autenticado"
on public.consultas
for delete
to authenticated
using (true);
