-- Art Dental v0.4
-- Odontograma interativo com histórico por paciente
-- Execute APÓS supabase-v0.3.sql

-- =====================================================
-- ODONTOGRAMA
-- Cada lançamento é imutável e preserva o histórico clínico.
-- O estado visual atual de cada dente é o registro mais recente.
-- =====================================================

create table if not exists public.odontograma_registros (
    id bigint generated by default as identity primary key,
    paciente_id bigint not null,
    dente smallint not null,
    condicao text not null,
    superficie text not null default 'Dente completo',
    observacoes text,
    registrado_por uuid not null default auth.uid(),
    criado_em timestamptz not null default now(),

    constraint odontograma_registros_paciente_id_fkey
        foreign key (paciente_id)
        references public.pacientes(id)
        on delete cascade,

    constraint odontograma_dente_valido check (
        dente in (
            18,17,16,15,14,13,12,11,
            21,22,23,24,25,26,27,28,
            48,47,46,45,44,43,42,41,
            31,32,33,34,35,36,37,38
        )
    ),

    constraint odontograma_condicao_valida check (
        condicao in (
            'Saudável',
            'Restauração',
            'Comprometido',
            'Tratamento necessário',
            'Tratamento concluído',
            'Ausente / extraído',
            'Endodontia / canal'
        )
    ),

    constraint odontograma_superficie_valida check (
        superficie in (
            'Dente completo',
            'Oclusal / Incisal',
            'Vestibular',
            'Lingual / Palatina',
            'Mesial',
            'Distal',
            'Raiz'
        )
    ),

    constraint odontograma_observacoes_tamanho check (
        observacoes is null or char_length(observacoes) <= 5000
    )
);

create index if not exists odontograma_paciente_idx
on public.odontograma_registros (paciente_id);

create index if not exists odontograma_paciente_dente_data_idx
on public.odontograma_registros (paciente_id, dente, criado_em desc, id desc);

-- =====================================================
-- SEGURANÇA
-- Histórico clínico: frontend pode consultar e adicionar registros.
-- Não há UPDATE/DELETE nesta versão para evitar sobrescrever histórico.
-- =====================================================

alter table public.odontograma_registros enable row level security;

revoke all on table public.odontograma_registros from anon;
revoke all on table public.odontograma_registros from authenticated;

grant select, insert
on table public.odontograma_registros
to authenticated;

grant usage, select
on sequence public.odontograma_registros_id_seq
to authenticated;

drop policy if exists "odontograma_select_autenticado" on public.odontograma_registros;
drop policy if exists "odontograma_insert_autenticado" on public.odontograma_registros;

create policy "odontograma_select_autenticado"
on public.odontograma_registros
for select
to authenticated
using (true);

create policy "odontograma_insert_autenticado"
on public.odontograma_registros
for insert
to authenticated
with check (
    registrado_por = auth.uid()
);
