-- Art Dental v0.2
-- Perfil do paciente, contato de emergência e arquivos privados
-- Execute APÓS supabase-pacientes.sql e supabase-consultas.sql

-- =====================================================
-- 1. NOVOS CAMPOS DO PACIENTE
-- =====================================================

alter table public.pacientes
add column if not exists contato_emergencia_nome text,
add column if not exists contato_emergencia_telefone text;

alter table public.pacientes
drop constraint if exists pacientes_contato_emergencia_telefone_valido;

alter table public.pacientes
add constraint pacientes_contato_emergencia_telefone_valido
check (
    contato_emergencia_telefone is null
    or contato_emergencia_telefone ~ '^[0-9]{10,11}$'
);

-- =====================================================
-- 2. METADADOS DOS ARQUIVOS
-- O arquivo binário fica no Supabase Storage.
-- Esta tabela guarda apenas o vínculo e informações do arquivo.
-- =====================================================

create table if not exists public.paciente_arquivos (
    id bigint generated by default as identity primary key,
    paciente_id bigint not null,
    nome_arquivo text not null,
    caminho_storage text not null unique,
    tipo_arquivo text,
    tamanho_bytes bigint,
    criado_em timestamptz not null default now(),

    constraint paciente_arquivos_paciente_id_fkey
        foreign key (paciente_id)
        references public.pacientes(id)
        on delete cascade,

    constraint paciente_arquivos_tamanho_valido
        check (tamanho_bytes is null or tamanho_bytes >= 0)
);

create index if not exists paciente_arquivos_paciente_idx
on public.paciente_arquivos (paciente_id);

create index if not exists paciente_arquivos_criado_em_idx
on public.paciente_arquivos (criado_em desc);

alter table public.paciente_arquivos enable row level security;

revoke all on table public.paciente_arquivos from anon;
grant select, insert, update, delete on table public.paciente_arquivos to authenticated;
grant usage, select on sequence public.paciente_arquivos_id_seq to authenticated;

drop policy if exists "paciente_arquivos_select_autenticado" on public.paciente_arquivos;
drop policy if exists "paciente_arquivos_insert_autenticado" on public.paciente_arquivos;
drop policy if exists "paciente_arquivos_update_autenticado" on public.paciente_arquivos;
drop policy if exists "paciente_arquivos_delete_autenticado" on public.paciente_arquivos;

create policy "paciente_arquivos_select_autenticado"
on public.paciente_arquivos
for select
to authenticated
using (true);

create policy "paciente_arquivos_insert_autenticado"
on public.paciente_arquivos
for insert
to authenticated
with check (true);

create policy "paciente_arquivos_update_autenticado"
on public.paciente_arquivos
for update
to authenticated
using (true)
with check (true);

create policy "paciente_arquivos_delete_autenticado"
on public.paciente_arquivos
for delete
to authenticated
using (true);

-- =====================================================
-- 3. STORAGE PRIVADO
-- Fotos e PDFs ficam no bucket paciente-arquivos.
-- Limite: 10 MB por arquivo.
-- Formatos: JPG, PNG, WEBP e PDF.
-- =====================================================

insert into storage.buckets (
    id,
    name,
    public,
    file_size_limit,
    allowed_mime_types
)
values (
    'paciente-arquivos',
    'paciente-arquivos',
    false,
    10485760,
    array[
        'image/jpeg',
        'image/png',
        'image/webp',
        'application/pdf'
    ]
)
on conflict (id) do update
set
    public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

-- Segurança do Storage. O bucket permanece privado.
drop policy if exists "paciente_storage_select_autenticado" on storage.objects;
drop policy if exists "paciente_storage_insert_autenticado" on storage.objects;
drop policy if exists "paciente_storage_update_autenticado" on storage.objects;
drop policy if exists "paciente_storage_delete_autenticado" on storage.objects;

create policy "paciente_storage_select_autenticado"
on storage.objects
for select
to authenticated
using (bucket_id = 'paciente-arquivos');

create policy "paciente_storage_insert_autenticado"
on storage.objects
for insert
to authenticated
with check (bucket_id = 'paciente-arquivos');

create policy "paciente_storage_update_autenticado"
on storage.objects
for update
to authenticated
using (bucket_id = 'paciente-arquivos')
with check (bucket_id = 'paciente-arquivos');

create policy "paciente_storage_delete_autenticado"
on storage.objects
for delete
to authenticated
using (bucket_id = 'paciente-arquivos');
