-- Art Dental - tabela de pacientes
-- Execute este arquivo no Supabase em: SQL Editor > New query > Run

create table if not exists public.pacientes (
    id bigint generated by default as identity primary key,
    nome text not null,
    cpf text unique,
    nascimento date,
    telefone text not null,
    email text,
    endereco text,
    criado_em timestamptz not null default now(),
    atualizado_em timestamptz not null default now(),

    constraint pacientes_nome_valido check (char_length(trim(nome)) >= 2),
    constraint pacientes_cpf_valido check (cpf is null or cpf ~ '^[0-9]{11}$'),
    constraint pacientes_telefone_valido check (telefone ~ '^[0-9]{10,11}$')
);

-- Permissões da API: usuário não autenticado não acessa os dados.
revoke all on table public.pacientes from anon;
grant select, insert, update, delete on table public.pacientes to authenticated;
grant usage, select on sequence public.pacientes_id_seq to authenticated;

-- Mantém atualizado_em automaticamente ao editar um paciente.
create or replace function public.atualizar_timestamp_paciente()
returns trigger
language plpgsql
set search_path = public
as $$
begin
    new.atualizado_em = now();
    return new;
end;
$$;

drop trigger if exists pacientes_atualizado_em on public.pacientes;

create trigger pacientes_atualizado_em
before update on public.pacientes
for each row
execute function public.atualizar_timestamp_paciente();

-- Segurança por linha: somente usuários autenticados podem acessar pacientes.
alter table public.pacientes enable row level security;

drop policy if exists "pacientes_select_autenticado" on public.pacientes;
drop policy if exists "pacientes_insert_autenticado" on public.pacientes;
drop policy if exists "pacientes_update_autenticado" on public.pacientes;
drop policy if exists "pacientes_delete_autenticado" on public.pacientes;

create policy "pacientes_select_autenticado"
on public.pacientes
for select
to authenticated
using (true);

create policy "pacientes_insert_autenticado"
on public.pacientes
for insert
to authenticated
with check (true);

create policy "pacientes_update_autenticado"
on public.pacientes
for update
to authenticated
using (true)
with check (true);

create policy "pacientes_delete_autenticado"
on public.pacientes
for delete
to authenticated
using (true);

-- Índices úteis para buscas e ordenação.
create index if not exists pacientes_nome_idx on public.pacientes (nome);
create index if not exists pacientes_telefone_idx on public.pacientes (telefone);
