-- Art Dental v0.3
-- Anamnese e plano de tratamento com histórico de versões
-- Execute APÓS supabase-v0.2.sql

-- =====================================================
-- 1. ANAMNESE
-- Um registro atual por paciente. Atualizações preservam criado_em
-- e renovam atualizado_em automaticamente.
-- =====================================================

create table if not exists public.anamneses (
    id bigint generated by default as identity primary key,
    paciente_id bigint not null unique,

    possui_doencas boolean not null default false,
    doencas_detalhes text,

    usa_medicamentos boolean not null default false,
    medicamentos_detalhes text,

    possui_alergias boolean not null default false,
    alergias_detalhes text,

    cirurgias_hospitalizacoes text,

    hipertensao boolean not null default false,
    diabetes boolean not null default false,
    cardiopatia boolean not null default false,

    outras_condicoes text,
    observacoes text,

    criado_em timestamptz not null default now(),
    atualizado_em timestamptz not null default now(),

    constraint anamneses_paciente_id_fkey
        foreign key (paciente_id)
        references public.pacientes(id)
        on delete cascade
);

create index if not exists anamneses_paciente_idx
on public.anamneses (paciente_id);

create or replace function public.atualizar_timestamp_anamnese()
returns trigger
language plpgsql
set search_path = public
as $$
begin
    new.atualizado_em = now();
    return new;
end;
$$;

drop trigger if exists anamneses_atualizado_em on public.anamneses;

create trigger anamneses_atualizado_em
before update on public.anamneses
for each row
execute function public.atualizar_timestamp_anamnese();

alter table public.anamneses enable row level security;

revoke all on table public.anamneses from anon;
grant select, insert, update, delete on table public.anamneses to authenticated;
grant usage, select on sequence public.anamneses_id_seq to authenticated;

drop policy if exists "anamneses_select_autenticado" on public.anamneses;
drop policy if exists "anamneses_insert_autenticado" on public.anamneses;
drop policy if exists "anamneses_update_autenticado" on public.anamneses;
drop policy if exists "anamneses_delete_autenticado" on public.anamneses;

create policy "anamneses_select_autenticado"
on public.anamneses
for select
to authenticated
using (true);

create policy "anamneses_insert_autenticado"
on public.anamneses
for insert
to authenticated
with check (true);

create policy "anamneses_update_autenticado"
on public.anamneses
for update
to authenticated
using (true)
with check (true);

create policy "anamneses_delete_autenticado"
on public.anamneses
for delete
to authenticated
using (true);

-- =====================================================
-- 2. PLANOS DE TRATAMENTO
-- Cada salvamento cria uma nova versão para manter histórico.
-- O plano atual é sempre o registro mais recente do paciente.
-- =====================================================

create table if not exists public.planos_tratamento (
    id bigint generated by default as identity primary key,
    paciente_id bigint not null,
    conteudo text not null,
    criado_em timestamptz not null default now(),

    constraint planos_tratamento_paciente_id_fkey
        foreign key (paciente_id)
        references public.pacientes(id)
        on delete cascade,

    constraint planos_tratamento_conteudo_valido
        check (char_length(trim(conteudo)) > 0)
);

create index if not exists planos_tratamento_paciente_idx
on public.planos_tratamento (paciente_id);

create index if not exists planos_tratamento_paciente_data_idx
on public.planos_tratamento (paciente_id, criado_em desc);

alter table public.planos_tratamento enable row level security;

revoke all on table public.planos_tratamento from anon;
grant select, insert, update, delete on table public.planos_tratamento to authenticated;
grant usage, select on sequence public.planos_tratamento_id_seq to authenticated;

drop policy if exists "planos_tratamento_select_autenticado" on public.planos_tratamento;
drop policy if exists "planos_tratamento_insert_autenticado" on public.planos_tratamento;
drop policy if exists "planos_tratamento_update_autenticado" on public.planos_tratamento;
drop policy if exists "planos_tratamento_delete_autenticado" on public.planos_tratamento;

create policy "planos_tratamento_select_autenticado"
on public.planos_tratamento
for select
to authenticated
using (true);

create policy "planos_tratamento_insert_autenticado"
on public.planos_tratamento
for insert
to authenticated
with check (true);

create policy "planos_tratamento_update_autenticado"
on public.planos_tratamento
for update
to authenticated
using (true)
with check (true);

create policy "planos_tratamento_delete_autenticado"
on public.planos_tratamento
for delete
to authenticated
using (true);
