-- Art Dental v0.5
-- Acompanhamento do tratamento

create table if not exists public.acompanhamento_tratamento (
    id bigint generated by default as identity primary key,
    paciente_id bigint not null,
    procedimento text not null,
    dente smallint,
    data_procedimento date not null default current_date,
    forma_pagamento text not null,
    observacoes text,
    registrado_por uuid not null default auth.uid(),
    criado_em timestamptz not null default now(),

    constraint acompanhamento_paciente_id_fkey
        foreign key (paciente_id)
        references public.pacientes(id)
        on delete cascade,

    constraint acompanhamento_procedimento_valido
        check (char_length(trim(procedimento)) between 2 and 300),

    constraint acompanhamento_dente_valido check (
        dente is null or dente in (
            18,17,16,15,14,13,12,11,
            21,22,23,24,25,26,27,28,
            48,47,46,45,44,43,42,41,
            31,32,33,34,35,36,37,38
        )
    ),

    constraint acompanhamento_pagamento_valido check (
        forma_pagamento in (
            'PIX',
            'Dinheiro',
            'Cartão de débito',
            'Cartão de crédito',
            'Transferência',
            'Convênio',
            'Cortesia',
            'Outro'
        )
    ),

    constraint acompanhamento_observacoes_tamanho check (
        observacoes is null or char_length(observacoes) <= 5000
    )
);

create index if not exists acompanhamento_paciente_data_idx
on public.acompanhamento_tratamento (paciente_id, data_procedimento desc, id desc);

alter table public.acompanhamento_tratamento enable row level security;

revoke all on table public.acompanhamento_tratamento from anon;
revoke all on table public.acompanhamento_tratamento from authenticated;

grant select, insert on table public.acompanhamento_tratamento to authenticated;
grant usage, select on sequence public.acompanhamento_tratamento_id_seq to authenticated;

drop policy if exists "acompanhamento_select_autenticado" on public.acompanhamento_tratamento;
drop policy if exists "acompanhamento_insert_autenticado" on public.acompanhamento_tratamento;

create policy "acompanhamento_select_autenticado"
on public.acompanhamento_tratamento
for select
to authenticated
using (true);

create policy "acompanhamento_insert_autenticado"
on public.acompanhamento_tratamento
for insert
to authenticated
with check (registrado_por = auth.uid());
