-- Art Dental v0.6
-- Documentos: Termo de Responsabilidade com assinatura manuscrita eletrônica

-- =====================================================
-- TABELA DE DOCUMENTOS ASSINADOS
-- Documentos são append-only no frontend: SELECT + INSERT.
-- =====================================================

create table if not exists public.documentos_paciente (
    id bigint generated by default as identity primary key,
    paciente_id bigint not null,
    tipo text not null default 'Termo de responsabilidade',
    versao_modelo text not null default '1.0',
    conteudo text not null,
    nome_assinante text not null,
    cpf_assinante text,
    nome_arquivo text not null,
    caminho_storage text not null unique,
    hash_sha256 text not null,
    assinado_em timestamptz not null default now(),
    registrado_por uuid not null default auth.uid(),
    criado_em timestamptz not null default now(),

    constraint documentos_paciente_id_fkey
        foreign key (paciente_id)
        references public.pacientes(id)
        on delete restrict,

    constraint documentos_tipo_valido
        check (char_length(trim(tipo)) between 3 and 120),

    constraint documentos_versao_valida
        check (char_length(trim(versao_modelo)) between 1 and 20),

    constraint documentos_conteudo_valido
        check (char_length(trim(conteudo)) >= 20),

    constraint documentos_assinante_valido
        check (char_length(trim(nome_assinante)) between 2 and 160),

    constraint documentos_cpf_valido
        check (cpf_assinante is null or cpf_assinante ~ '^[0-9]{11}$'),

    constraint documentos_hash_valido
        check (hash_sha256 ~ '^[a-f0-9]{64}$')
);

create index if not exists documentos_paciente_data_idx
on public.documentos_paciente (paciente_id, assinado_em desc, id desc);

alter table public.documentos_paciente enable row level security;

revoke all on table public.documentos_paciente from anon;
revoke all on table public.documentos_paciente from authenticated;

grant select, insert
on table public.documentos_paciente
to authenticated;

grant usage, select
on sequence public.documentos_paciente_id_seq
to authenticated;

drop policy if exists "documentos_select_autenticado" on public.documentos_paciente;
drop policy if exists "documentos_insert_autenticado" on public.documentos_paciente;

create policy "documentos_select_autenticado"
on public.documentos_paciente
for select
to authenticated
using (true);

create policy "documentos_insert_autenticado"
on public.documentos_paciente
for insert
to authenticated
with check (registrado_por = auth.uid());

-- =====================================================
-- STORAGE PRIVADO PARA DOCUMENTOS ASSINADOS
-- O frontend pode enviar e visualizar, mas não alterar/excluir.
-- =====================================================

insert into storage.buckets (
    id,
    name,
    public,
    file_size_limit,
    allowed_mime_types
)
values (
    'documentos-assinados',
    'documentos-assinados',
    false,
    5242880,
    array['application/pdf']
)
on conflict (id) do update
set
    public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "documentos_storage_select_autenticado" on storage.objects;
drop policy if exists "documentos_storage_insert_autenticado" on storage.objects;

create policy "documentos_storage_select_autenticado"
on storage.objects
for select
to authenticated
using (bucket_id = 'documentos-assinados');

create policy "documentos_storage_insert_autenticado"
on storage.objects
for insert
to authenticated
with check (bucket_id = 'documentos-assinados');
